app:
  editor: auto_editor
  default_threshold: '-40dB'
server:
  host: localhost
  port: 8080
  debug: false
paths:
  templates_dir: ./templates
  output_dir: ./output
  temp_dir: /tmp/autocutstudio
  assets:
    backgrounds:
      space_background: /Volumes/Callisto/Movies/FCPX/assets/earth background.png
    borders:
      cam_dc:
        top_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/cam dc top left.png
        bottom_right: /Volumes/Callisto/Movies/FCPX/assets/white boxes/cam dc bottom right.png
      gs:
        bottom_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/gs bottom left.png
        bottom_right: /Volumes/Callisto/Movies/FCPX/assets/white boxes/gs bottom right.png
        top_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/gs top left.png
      gs_dc:
        bottom_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/gs dc bottom left.png
        bottom_right: /Volumes/Callisto/Movies/FCPX/assets/white boxes/gs dc bottom right.png
        top_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/gs dc top left.png
        top_right: /Volumes/Callisto/Movies/FCPX/assets/white boxes/gs dc top right.png
      ssb:
        top_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/ssb top left.png
        bottom_right: /Volumes/Callisto/Movies/FCPX/assets/white boxes/ssb bottom right.png
      ssb_dc:
        top_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/ssb dc top left.png
        bottom_left: /Volumes/Callisto/Movies/FCPX/assets/white boxes/ssb dc bottom left.png
        bottom_right: /Volumes/Callisto/Movies/FCPX/assets/white boxes/ssb dc bottom right.png
      shorts:
        border: /Volumes/Callisto/Movies/FCPX/assets/white boxes/shorts border.png
source_layouts:
  master_current:
    type: master_multi
    camera1:
      crop:
        - 2.08966
        - 51.343
        - 90.9273
        - 1.61006
      scale: 1
    camera2:
      crop:
        - 0
        - 0
        - 50
        - 50
      scale: 1
    screen:
      crop:
        - 0
        - 0
        - 100
        - 100
      scale: 1
    game:
      crop:
        - 50
        - 50
        - 100
        - 100
      scale: 1
  individual_files:
    type: individual
current_layout: master_current
layouts:
  cam:
    solo:
      camera:
        lane: 1
        scale: 2.13
        position:
          - 94.5832
          - 53.0757
        crop:
          - 2.08966
          - 51.343
          - 90.9273
          - 1.61006
        transform_mode: trim
      audio_sources:
        - mic1
        - mic2
        - mic3
        - mic4
        - soundEffects
      gap:
        name: Gap
    dual:
      cam1:
        lane: 1
        scale: 1
        position:
          - 25
          - 25
        crop:
          - 0
          - 0
          - 50
          - 50
        border: cam_dc.top_left
      cam2:
        lane: 2
        scale: 1
        position:
          - 75
          - 75
        crop:
          - 50
          - 50
          - 100
          - 100
        border: cam_dc.bottom_right
      background: space_background
      audio_sources:
        - mic1
        - mic2
        - mic3
        - mic4
        - soundEffects
      gap:
        name: Gap
  gs:
    solo:
      camera:
        lane: 1
        position:
          - 25
          - 75
        scale: 1
        border: gs.bottom_left
      game:
        lane: 2
        position:
          - 75
          - 75
        scale: 1
        border: gs.bottom_right
      screen:
        lane: 3
        position:
          - 25
          - 25
        scale: 1
        border: gs.top_left
      background: space_background
      audio_sources:
        - mic1
        - mic2
        - mic3
        - mic4
        - screen
        - game
        - soundEffects
        - bluetooth
    dual:
      camera:
        lane: 1
        position:
          - 25
          - 75
        scale: 1
        border: gs_dc.bottom_left
      cam2:
        lane: 2
        position:
          - 75
          - 25
        scale: 1
        border: gs_dc.top_right
      game:
        lane: 3
        position:
          - 75
          - 75
        scale: 1
        border: gs_dc.bottom_right
      screen:
        lane: 4
        position:
          - 25
          - 25
        scale: 1
        border: gs_dc.top_left
      background: space_background
      audio_sources:
        - mic1
        - mic2
        - mic3
        - mic4
        - screen
        - game
        - soundEffects
        - bluetooth
  ssb:
    solo:
      camera:
        lane: 1
        position:
          - 25
          - 25
        scale: 1
        border: ssb.top_left
      screen:
        lane: 2
        position:
          - 75
          - 75
        scale: 1.5
        border: ssb.bottom_right
      background: space_background
      audio_sources:
        - screen
        - game
        - bluetooth
    dual:
      cam1:
        lane: 1
        position:
          - 25
          - 25
        scale: 1
        border: ssb_dc.top_left
      cam2:
        lane: 2
        position:
          - 25
          - 75
        scale: 1
        border: ssb_dc.bottom_left
      screen:
        lane: 3
        position:
          - 75
          - 75
        scale: 1.5
        border: ssb_dc.bottom_right
      background: space_background
      audio_sources:
        - screen
        - game
        - bluetooth
  shorts_cam:
    solo:
      camera:
        lane: 1
        crop:
          - 0
          - 50.0412
          - 88.8889
          - 0
        position:
          - 89.2019
          - 50.291
        scale: 6.3576
      audio_sources:
        - mic1
        - mic2
        - mic3
        - mic4
        - soundEffects
    dual:
      cam1:
        lane: 1
        crop:
          - 0
          - 50.0412
          - 88.8889
          - 0
        position:
          - 46.1833
          - -0.103782
        scale: 3.2
      cam2:
        lane: 2
        crop:
          - 88.8889
          - 0
          - 0
          - 50.0412
        position:
          - -43.1878
          - -0.498011
        scale: 3.2
      audio_sources:
        - mic1
        - mic2
        - mic3
        - mic4
        - soundEffects
  shorts_ssb:
    solo:
      screen:
        lane: 1
        crop:
          - 0
          - 0
          - 88.8889
          - 50.0412
        position:
          - 89.3698
          - -50.4281
        scale: 6.3619
      camera:
        lane: 2
        crop:
          - 0
          - 50.0412
          - 88.8889
          - 0
        position:
          - 24.4792
          - -18.2292
        scale: 1.75
        border: shorts.border
        border_position:
          - 0
          - 4.42708
        border_scale: 1.4
      audio_sources:
        - screen
        - game
        - bluetooth
    dual:
      screen:
        lane: 1
        crop:
          - 0
          - 0
          - 88.8889
          - 50.0412
        position:
          - 89.3698
          - -50.4281
        scale: 6.3619
      cam1:
        lane: 2
        crop:
          - 0
          - 50.0412
          - 88.8889
          - 0
        position:
          - 5.52029
          - -17.6981
        scale: 1.15
        border: shorts.border
        border_position:
          - -10.6878
          - -2.73181
        border_scale: 0.92
      cam2:
        lane: 4
        crop:
          - 88.8889
          - 0
          - 0
          - 50.0412
        position:
          - -5.74915
          - -48.3457
        scale: 1.15
        border: shorts.border
        border_position:
          - 10.3731
          - -15.2241
        border_scale: 0.92
      audio_sources:
        - screen
        - game
        - bluetooth
file_patterns:
  master: '{date} master'
  cam: '{date} cam'
  mic1: '{date} mic1'
  mic2: '{date} mic2'
  mic3: '{date} mic3'
  mic4: '{date} mic4'
  screen: '{date} screen'
  game: '{date} game'
  soundEffects: '{date} sound effects'
  bluetooth: '{date} bluetooth'
editors:
  auto_editor:
    command: auto-editor
    export_format: final-cut-pro
    supported_formats:
      - .mp4
      - .mov
      - .avi
      - .mkv
      - .flv
      - .wmv
      - .mpg
      - .mpeg
      - .m4v
      - .webm
audio:
  sync_correction: 1.001
  sample_rate: 48000
  supported_formats:
    - .wav
    - .mp3
    - .aac
    - .flac
    - .ogg
  sources:
    mic1: null
    mic2: null
    mic3: null
    mic4: null
    screen: null
    game: null
    soundEffects: null
    bluetooth: null
video:
  frame_duration: 1001/30000s
  width: 1920
  height: 1080
  color_space: 1-1-1 (Rec. 709)
  tcFormat: NDF
  audioLayout: stereo
  audioRate: 48k

video_shorts:
  frame_duration: 1001/30000s
  width: 1080
  height: 1920
  color_space: 1-1-1 (Rec. 709)
  tcFormat: NDF
  audioLayout: stereo
  audioRate: 48k
